### ISSUE TITLE
Changing description does nothing

### ISSUE THREAD

**Issue by ghost** [darealshinji/UnityEngine2deb#2] opened 2017-05-19 16:20 UTC
Changing the text in the u2deb folder in "/tmp" does nothing to change the description that shows up in gdebbi. I have tried changing both the top level description file as well as the one located at "/tmp/[u2deb_folder]/build/x86/debian".

**Comment by darealshinji** [comment] 2017-05-19 17:34
I will give it a try.

**Comment by darealshinji** [comment] 2017-05-19 19:08
Weird, I have no problems with it. You did edit the descriptions before running `./u2deb build` right?

**Comment by ghost** [comment] 2017-05-20 18:36
I did. I'll take a closer look at the code tonight and see if I can find where it is hanging up.

**Comment by darealshinji** [comment] 2017-05-22 13:18
Anything found yet? What distro are you using? I'm on Ubuntu 16.04. I doubt it, but maybe there's something different on yours that is causing the issue.
Or maybe I should change the way how a long description is added?

**Comment by ghost** [comment] 2017-05-22 13:22
Everything I've seen so far indicates it should be working fine. I'm looking into other places in the code that it might be overwritten. I am on Mint 18.1 using GDebi to manage the package. It is in GDebi that I am not seeing the change in the description.

**Comment by darealshinji** [comment] 2017-05-22 13:41
I will download Mint 18.1 and see if I can reproduce the issue.

**Comment by ghost** [comment] 2017-05-22 13:44
I wouldn't think that it would be the cause since, underneath, Ubuntu and Mint are the same. I'll be installing a new Mint spinoff, Feren OS, today on a new PC and am going to try there as well.

**Comment by darealshinji** [comment] 2017-05-24 17:27
I've checked it on Mint 18.1 and couldn't reproduce the bug.

Each time you invoke  `u2deb prepare` a new temporary directory with a different name is created. Are you sure you didn't accidentally edit the description inside an old directory that wasn't deleted?

**Comment by ghost** [comment] 2017-05-25 13:04
I have verified that it is working on feren OS 2017.1. I was making sure to edit the correct temporary directory previously, but with it working now for me and your tests also working fine on Mint I think we can assume it was something I was doing wrong.

**Comment by darealshinji** [comment] 2017-07-10 06:56
I'm closing this. Just open if the problem happens again.

**Closed as completed by darealshinji** 2017-07-10 06:56 UTC
Labels: bug
